### ISSUE TITLE
Responsive edgePadding new value not being set

### ISSUE THREAD

**Issue by harrymamba** [ganlanyuan/tiny-slider#111]
edgePadding doesn't get set to the new value on responsive option. It works OK on default setting but when screen meets the breakpoint the initial edgePadding is still there and didn't honor the new value on the breakpoint.

__Demo link/slider setting__:   
```
{
      container: '.recommendations',
      items: 1,
      autoplay: false,
      nav: false,
      autoHeight: true,
      slideBy: 1,
      gutter: 10,
      controlsContainer: '#controlsContainer',
      edgePadding: 20,
      responsive: {
        601: {
          items: 3,
          edgePadding: 0,
          gutter: 20,
          controls: true,
          slideBy: 4,
        },
        960: {
          items: 4,
        },
      },
    }
```

_Tiny-slider version_:   2.2.5
_Browser name && version_:  Chrome
_OS name && version_:   OSX

**Comment by ganlanyuan** [comment]
Hey @harrymamba ,
Could you try the latest version of tiny-slider?
I remember this issue was fixed before.

**Comment by ganlanyuan** [comment]
related to #100

**Comment by harrymamba** [comment]
Yeah. I did try to update. Issue still exist. Was able to get away with it by overriding the margin of `#tns1-iw`. edgePadding works if the config is like 
```
{
  edgePadding: 0
  gutter: 10,
  responsive {
     700: {
         edgePadding: 20
         gutter: 20,
     },
  },
}
```
but doesn't if it starts with an edgePadding value and resets it to 0 on the larger screen size.
```
{
  edgePadding: 10
  gutter: 10,
  responsive {
     700: {
         edgePadding: 0
         gutter: 20,
     },
  },
}
```

**Comment by xserber** [comment]
I confirm the bug exists. Chrome browser test. Ubuntu.
My temporary fix is ​​to ask margin for element .tns-inner

**Comment by ganlanyuan** [comment]
Thanks @harrymamba and @xserber 
This issue should be fixed in [v2.3.7](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.3.7)

**Comment by harrymamba** [comment]
Looks like this one is fixed! 👍

**Comment by RainbowBunchie** [comment]
Having the issue still in v2.8.7 in Chrome

**Comment by TitanFighter** [comment]
Hi @ganlanyuan . Thank for this nice slider!
It seems I can confirm this bug.
Here is [the demo](https://jsfiddle.net/mgb0eLfy/6/).
Also it seems that this bug also influence at least `gutter` option (in my project it does not work in the same way as `edgePadding` in the demo shown above).

**Comment by ganlanyuan** [comment]
@TitanFighter This should be fixed in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/cab3863ad3043edd0517099061d1763fb5de6392).
Let me know if it works for you. thanks

**Comment by TitanFighter** [comment]
@ganlanyuan I checked the commit.

If the case, when smaller breakpoint option applies to higher breakpoints until higher breakpoint changes the value of the option, is expected behavior, then I confirm that the bug is fixed.

I think, few words about such behavior in the README (`Responsive options` block) could be useful.

I would be grateful if you can update npm. Thank you!

**Comment by ganlanyuan** [comment]
> If the case, when smaller breakpoint option applies to higher breakpoints (until higher breakpoint changes the value of the option) is expected behavior, 

Exactly,
README updated.
