### ISSUE TITLE
Exception when destroying a slider

### ISSUE THREAD

**Issue by planktonic** [ganlanyuan/tiny-slider#255]
__Issue description__:
When `destroy`ing then re-instantiating a slider on viewport resizing (with different options)  i.e. within a `window.watchMedia` listener: an exception is thrown and the slider is not destroyed successfully:

```
TypeError: null is not an object (evaluating 'n.parentNode.firstElementChild')
(anonymous function) — tiny-slider.js:1551
forEach
destroy — tiny-slider.js:1545
initialiseSlider — index.html:75
j — everypage-0e95adae4bb69d30b4cb02bf3e2b442d3bfbc0ebb7e5cb2983d7a2ab7cc9bb52.js:1:3941
get — everypage-0e95adae4bb69d30b4cb02bf3e2b442d3bfbc0ebb7e5cb2983d7a2ab7cc9bb52.js:2:26712
css — everypage-0e95adae4bb69d30b4cb02bf3e2b442d3bfbc0ebb7e5cb2983d7a2ab7cc9bb52.js:2:26408
(anonymous function) — everypage-0e95adae4bb69d30b4cb02bf3e2b442d3bfbc0ebb7e5cb2983d7a2ab7cc9bb52.js:3:18213
access — everypage-0e95adae4bb69d30b4cb02bf3e2b442d3bfbc0ebb7e5cb2983d7a2ab7cc9bb52.js:2:5963
(anonymous function) — everypage-0e95adae4bb69d30b4cb02bf3e2b442d3bfbc0ebb7e5cb2983d7a2ab7cc9bb52.js:3:17982
M — index-91133e28b0e3348db53bd3f3086f8328b5dabc10f96e2a76a7b0c5e584f15751.js:5:32198
P — index-91133e28b0e3348db53bd3f3086f8328b5dabc10f96e2a76a7b0c5e584f15751.js:5:31419
C — index-91133e28b0e3348db53bd3f3086f8328b5dabc10f96e2a76a7b0c5e584f15751.js:5:31085
emitEvent — commonLibs-361493429bb9f80462ff7ccdbe48cb444552cda5f0655ec0f127e7fbf0d5444d.js:3:16688
dragMove — commonLibs-361493429bb9f80462ff7ccdbe48cb444552cda5f0655ec0f127e7fbf0d5444d.js:3:24379
_dragMove — commonLibs-361493429bb9f80462ff7ccdbe48cb444552cda5f0655ec0f127e7fbf0d5444d.js:3:24314
pointerMove — commonLibs-361493429bb9f80462ff7ccdbe48cb444552cda5f0655ec0f127e7fbf0d5444d.js:3:23477
_pointerMove — commonLibs-361493429bb9f80462ff7ccdbe48cb444552cda5f0655ec0f127e7fbf0d5444d.js:3:20518
onmousemove — commonLibs-361493429bb9f80462ff7ccdbe48cb444552cda5f0655ec0f127e7fbf0d5444d.js:3:20228
handleEvent — commonLibs-361493429bb9f80462ff7ccdbe48cb444552cda5f0655ec0f127e7fbf0d5444d.js:3:18878
2tiny-slider.js:1550
```
__Demo link/slider setting__:   
https://codepen.io/darrencadwallader/pen/MBdQgz

_Tiny-slider version_:   2.8.5
_Browser name && version_: Safari 11.1.2, Chrome 68.0.3440.106 
_OS name && version_:   macOS 10.13.6 (17G65)

**Comment by ganlanyuan** [comment]
Fixed in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/f17a1776d25ab7897e01f220c39926904094dd80).

**Comment by planktonic** [comment]
Thanks so much, this fix works for me! I look forward to the next release :)

**Comment by Suruat** [comment]
@ganlanyuan Still receiving 'TypeError: i.parentNode is null'

**Comment by Suruat** [comment]
@ganlanyuan Please, update npm package. Thank you in advance!

**Comment by planktonic** [comment]
@Suruat if it’s super-urgent, you could change the entry in your `package.json` to:
```
"tiny-slider": "git+https://github.com/ganlanyuan/tiny-slider#55a846549e07ce1129420296d598454db8e5a147"
```

…though you’ll need to remember to change it back to the normal version later.
