### ISSUE TITLE
Does not use passive listeners to improve scrolling performance after 2.8.8

### ISSUE THREAD

**Issue by stukalin** [ganlanyuan/tiny-slider#342]
__Issue description__:  After update to 2.8.8 the Lighthouse starts to complain that my page _Does not use passive listeners to improve scrolling performance_. I believe this is related to the latest changes in the `addEvents.js`.

_Tiny-slider version_:   2.8.8
_Browser name && version_:  Chrome
_OS name && version_:  Windows 10

**Comment by ganlanyuan** [comment]
Fixed in commit ad93eeb

**Comment by terrapop** [comment]
This issue still persists when adding option preventScrollOnTouch is set to "auto" or "force"

Please do not use non-passive event listeners.
